services:
  spark-worker-2:
    image: apache/spark
    user: root
    container_name: spark-worker-2
    command: sh -c "pip install python-dotenv numpy && /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://${SPARK_MASTER_HOST}:${SPARK_MASTER_PORT}"
    environment:
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
    ports:
      - "8082:8081"

