services:
  spark-master:
    image: apache/spark
    container_name: spark-master
    user: root
    command: sh -c "pip install python-dotenv numpy && /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "8080:8080"
      - "${SPARK_MASTER_PORT}:${SPARK_MASTER_PORT}"
    volumes:
      - ./code:/opt/spark/code 

  spark-worker-1:
    image: apache/spark
    container_name: spark-worker-1
    depends_on:
      - spark-master
    user: root
    command: sh -c "pip install python-dotenv numpy && /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://${SPARK_MASTER_HOST}:${SPARK_MASTER_PORT}"
    volumes:
      - ./code:/opt/spark/code
    ports:
      - "8081:8081"

